version: '3.7'

volumes:
    resume-dbdata:

services:
    resume-app:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "9000:9000"
        restart: unless-stopped
        networks:
            - bridge-network
    resume-nginx:
        build:
            context: ./
            dockerfile: ./docker/nginx/Dockerfile
        container_name: resume-nginx
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - /var/www/tls:/var/www/tls
        ports:
            - "80:80"
            - "443:443"
        restart: unless-stopped
        depends_on:
            - resume-app
            - resume-db
        networks:
            - bridge-network
    resume-db:
        image: 'mysql:8.0'
        container_name: resume-db
        volumes:
            - resume-dbdata:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        ports:
            - "3306:3306"
        restart: unless-stopped
        networks:
            - bridge-network
networks:
  bridge-network:
    driver: bridge
